[package]
name = "thoth-export-server"
version = "0.11.4"
authors = ["Javier Arias <javi@openbookpublishers.com>", "Ross Higman <ross@openbookpublishers.com>"]
edition = "2018"
license = "Apache-2.0"
description = "Actix instance serving Thoth's metadata export endpoints"
repository = "https://github.com/thoth-pub/thoth"
readme = "README.md"

[dependencies]
thoth-api = { version = "0.11.4", path = "../thoth-api" }
thoth-errors = { version = "0.11.4", path = "../thoth-errors" }
thoth-client = { version = "0.11.4", path = "../thoth-client" }
actix-web = "4.3.0"
actix-cors = "0.6.4"
cc_license = "0.1.0"
chrono = { version = "0.4.26", features = ["serde"] }
csv = "1.1.6"
env_logger = "0.10.0"
futures = "0.3.26"
lazy_static = "1.4.0"
log = "0.4.14"
marc = { version = "3.1.1", features = ["xml"] }
paperclip = { version = "0.8.0", features = ["actix-base", "actix4", "uuid0", "v2"] }
serde = { version = "1.0.115", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "0.8.2", features = ["serde"] }
xml-rs = "0.8.0"

[dev-dependencies]
regex = "1.6.0"
