[package]
name = "thoth-api"
version = "0.11.18"
authors = ["Javier Arias <javi@openbookpublishers.com>", "Ross Higman <ross@openbookpublishers.com>"]
edition = "2021"
license = "Apache-2.0"
description = "GraphQL API for bibliographic data"
repository = "https://github.com/thoth-pub/thoth"
readme = "README.md"

[badges]
travis-ci = { repository = "openbookpublishers/thoth" }
maintenance = { status = "actively-developed" }

[features]
backend = ["diesel", "diesel-derive-enum", "diesel_migrations", "futures", "actix-web", "jsonwebtoken"]

[dependencies]
thoth-errors = { version = "0.11.18", path = "../thoth-errors" }
actix-web = { version = "4.5.1", optional = true }
argon2rs = "0.2.5"
isbn2 = "0.4.0"
chrono = { version = "0.4.31", features = ["serde"] }
diesel = { version = "2.1.3", features = ["postgres", "uuid", "chrono", "r2d2", "64-column-tables", "serde_json"], optional = true }
diesel-derive-enum = { version = "2.1.0", features = ["postgres"], optional = true }
diesel-derive-newtype = "2.1.0"
diesel_migrations = { version = "2.1.0", features = ["postgres"], optional = true }
dotenv = "0.15.0"
futures = { version  = "0.3.29", optional = true }
jsonwebtoken = { version = "9.2.0", optional = true }
juniper = "0.15.12"
lazy_static = "1.4.0"
phf = { version = "0.11", features = ["macros"] }
rand = "0.8.5"
regex = "1.10.2"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"
strum = { version = "0.26.1", features = ["derive"] }
uuid = { version = "0.8.2", features = ["serde", "v4"] }

[dev-dependencies]
cargo-husky = { version = "1.5.0", default-features = false, features = ["prepush-hook", "run-cargo-check", "run-cargo-test", "run-cargo-clippy", "run-cargo-fmt"] }
