[package]
name = "thoth-client"
version = "0.11.9"
authors = ["Javier Arias <javi@openbookpublishers.com>", "Ross Higman <ross@openbookpublishers.com>"]
edition = "2018"
license = "Apache-2.0"
description = "GraphQL Client for bibliographic data"
repository = "https://github.com/thoth-pub/thoth"
readme = "README.md"

[dependencies]
thoth-api = {version = "0.11.9", path = "../thoth-api" }
thoth-errors = {version = "0.11.9", path = "../thoth-errors" }
graphql_client = "0.13.0"
chrono = { version = "0.4.31", features = ["serde"] }
reqwest = { version = "0.11", features = ["json"] }
reqwest-middleware = "0.2.3"
reqwest-retry = "0.2.3"
serde = "1.0"
serde_json = "1.0"
uuid = { version = "0.8.2", features = ["serde"] }
