[package]
name = "thoth-api-server"
version = "0.11.4"
authors = ["Javier Arias <javi@openbookpublishers.com>", "Ross Higman <ross@openbookpublishers.com>"]
edition = "2018"
license = "Apache-2.0"
description = "Actix instance serving Thoth's GraphQL endpoints"
repository = "https://github.com/thoth-pub/thoth"
readme = "README.md"

[dependencies]
thoth-api = { version = "0.11.4", path = "../thoth-api", features = ["backend"] }
thoth-errors = { version = "0.11.4", path = "../thoth-errors" }
actix-web = "4.4.0"
actix-cors = "0.6.4"
actix-identity = "0.5.2"
actix-session = { version = "0.7.2", features = ["cookie-session"] }
env_logger = "0.10.0"
juniper = "0.15.10"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
