[package]
name = "thoth-api-server"
version = "0.11.18"
authors = ["Javier Arias <javi@openbookpublishers.com>", "Ross Higman <ross@openbookpublishers.com>"]
edition = "2021"
license = "Apache-2.0"
description = "Actix instance serving Thoth's GraphQL endpoints"
repository = "https://github.com/thoth-pub/thoth"
readme = "README.md"

[dependencies]
thoth-api = { version = "0.11.18", path = "../thoth-api", features = ["backend"] }
thoth-errors = { version = "0.11.18", path = "../thoth-errors" }
actix-web = "4.5.1"
actix-cors = "0.7.0"
actix-identity = "0.7.1"
actix-session = { version = "0.9.0", features = ["cookie-session"] }
env_logger = "0.11.2"
juniper = "0.15.12"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
