[package]
name = "thoth-errors"
version = "0.11.4"
authors = ["Javier Arias <javi@openbookpublishers.com>", "Ross Higman <ross@openbookpublishers.com>"]
edition = "2018"
license = "Apache-2.0"
description = "Errors library for Thoth"
repository = "https://github.com/thoth-pub/thoth"
readme = "README.md"

[dependencies]
thiserror = "1.0"
reqwest = { version = "0.11", features = ["json"] }
serde = "1.0.115"
serde_json = "1.0"
uuid = { package = "uuid", version = "0.8.2", features = ["serde", "v4"] }
yewtil = { version = "0.4.0", features = ["fetch"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
actix-web = "4.4.0"
diesel = "2.1.1"
csv = "1.2.2"
juniper = "0.15.11"
marc = { version = "3.1.1", features = ["xml"] }
phf = { version = "0.11", features = ["macros"] }
reqwest-middleware = "0.2.3"
xml-rs = "0.8.17"
