name: check-changelog
on:
  pull_request:

jobs:
  check-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: tarides/changelog-check-action@v2
        with:
          changelog: CHANGELOG.md
